blank_issues_enabled: false
contact_links:
  - name: Suggest an improvement / Предложить улучшение
    url: https://github.com/DmitriySolomatin/Dockline-MacOS-Taskbar/discussions/categories/ideas
    about: Share an idea or support an existing one. Расскажите об идее или поддержите существующую.
  - name: Ask a question / Задать вопрос
    url: https://github.com/DmitriySolomatin/Dockline-MacOS-Taskbar/discussions/categories/q-a
    about: Get help using Dockline. Помощь с использованием приложения.
